title: Facial Emotion Recognition for Smart Homes Appliances
description: Shize Sheng, Yuanhong Zhou, Chunzhen Hu, Jiasheng Cao, Xingyu Hu
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
